# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-20 11:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DmartSale', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='dmart_user',
        ),
    ]
