# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-21 06:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DmartSale', '0002_auto_20190520_1153'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='dmart_user1',
        ),
    ]
