# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-21 07:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DmartSale', '0003_auto_20190521_0657'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='dmart_user',
        ),
    ]
