# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-21 10:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DmartSale', '0006_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
